### PR TITLE
Dumb board

### PR DESCRIPTION
**Pull request by JakeSucksAtProgramming**
If you can, only merge the new files. Do NOT merge the other file. I'm not sure what changed but it probably will fuck stuff up.

### CODE REVIEW

**Comment by kawfey** [comment]
which files are new?

**Comment by JakeSucksAtProgramming** [comment]
the two in the dumb-board folder. You should be able to tell on the web page.

-j

**Comment by JakeSucksAtProgramming** [comment]
FUCK IT WE'LL DO IT LIVE

**Comment by kawfey** [comment]
Oh god that was scary.

**Pull request merged**
