### PR TITLE
Sterdawg reroute 2 derp

### PR DESCRIPTION
**Pull request by JakeSucksAtProgramming**
Reroutes for Jesus

### CODE REVIEW

**Comment by kawfey** [comment]
Conflicts for satan. Necessitates command line proficient github operator for further action. 

#I Can't Even

**Comment by JakeSucksAtProgramming** [comment]
CANCEL IT ALL 
I AM NOT INTO COMMAND PROMPT DOT EXE

**Comment by JakeSucksAtProgramming** [comment]
let's just try this again.

**Comment by JakeSucksAtProgramming** [comment]
sterling I'm so afraid

**Comment by JakeSucksAtProgramming** [comment]
ok I backed up the files so I'm going to go for it

**Comment by kawfey** [comment]
Thank fuck that's over. I almost liquidated my assets and grabbed my bug-out bag for the apocalypse.

**Pull request merged**
